### ISSUE TITLE
無法login

### ISSUE THREAD

**Issue by 69you** [ccagml/leetcode-extension#292]
## 🐛 Bug Report(错误报告)

A clear and concise description of what the bug is.(清晰简洁地描述错误是什么。)

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)

## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)

## Extension Output(扩展输出)

```js
Node.js v18.17.1
c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\out\src\rpc\actionChain\chainNode\leetcode.js:484
            user.sessionId = cookieData.sessionId;
                                        ^

TypeError: Cannot read properties of undefined (reading 'sessionId')
    at LeetCode.cookieLogin (c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\out\src\rpc\actionChain\chainNode\leetcode.js:484:41)
    at c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\out\src\rpc\factory\api\userApi.js:127:56
    at c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\lib\prompt.js:358:32
    at wrapper (c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\node_modules\async\internal\once.js:12:16)
    at replenish (c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\node_modules\async\internal\eachOfLimit.js:76:25)
    at iterateeCallback (c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\node_modules\async\internal\eachOfLimit.js:65:17)
    at c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\node_modules\async\internal\onlyOnce.js:12:16
    at assembler (c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\lib\prompt.js:355:9)
    at c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\lib\prompt.js:364:32
    at c:\Users\you\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.1.16\node_modules\prompt\lib\prompt.js:659:5
```

## Your Environment

- _os(操作系统)_ window11
- _extension settings(扩展设置)_: 
- _nodejs version(nodejs 版本)_: 18.17.1
- _vscode version(vscode 版本)_:
- _extension version(扩展版本)_:

**Comment by wnykuang** [comment]
你是用什么方式login 的？
我比较推荐一种login 的方式：

- 使用chrome(mium) 浏览器
- 安装[vsleet](https://chromewebstore.google.com/detail/vsleet/ihgifhobfmjhcelknpbjhpabkcghjmfh?pli=1)
- 复制他给你选中的cache
- 在vscode 中使用cache 登陆

**Comment by ccagml** [comment]
这个看起来就是解析你传入的cookie没解析成功

**Comment by ccagml** [comment]
输入的cookie格式应该需要像这样子
csrftoken="xxxx"; LEETCODE_SESSION="xxxx";

**Comment by wnykuang** [comment]
> 这个看起来就是解析你传入的cookie没解析成功

你咋看出来他是cookie 登陆没成功的？

**Comment by Ciel-Z** [comment]
> 输入的cookie格式应该需要像这样子 csrftoken="xxxx"; LEETCODE_SESSION="xxxx";

建议把这个格式内置或者改为录入这两项。现在每次登录都来 github copy 一次 [捂脸]

**Comment by ccagml** [comment]
@wnykuang 看那个报错是正则解析cookie没解析出东西来,可能就是格式不对才没解析出来

**Comment by ccagml** [comment]
@Ciel-Z 确实这格式不好记

**Comment by 69you** [comment]
安裝了插件之後成功了 謝謝!
