### ISSUE TITLE
leetcode.cn  Cookies 登录失败

### ISSUE THREAD

**Issue by yfcube** [ccagml/leetcode-extension#339]
## 🐛 Bug Report(错误报告)

使用 cookies 登录失败，output中日志内容：
```

/home/fyf/.vscode/extensions/ccagml.vscode-leetcode-problem-rating-3.2.4/out/src/rpc/actionChain/chainNode/leetcode.js:654
                        user.paid = _user.isCurrentUserPremium;
                                          ^
TypeError: Cannot read properties of null (reading 'isCurrentUserPremium')
    at /home/fyf/.vscode/extensions/ccagml.vscode-leetcode-problem-rating-3.2.4/out/src/rpc/actionChain/chainNode/leetcode.js:654:43
    at Request._callback (/home/fyf/.vscode/extensions/ccagml.vscode-leetcode-problem-rating-3.2.4/out/src/rpc/actionChain/chainNode/leetcode.js:535:28)
    at self.callback (/home/fyf/.vscode/extensions/ccagml.vscode-leetcode-problem-rating-3.2.4/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/fyf/.vscode/extensions/ccagml.vscode-leetcode-problem-rating-3.2.4/node_modules/request/request.js:1161:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/fyf/.vscode/extensions/ccagml.vscode-leetcode-problem-rating-3.2.4/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)

Node.js v18.15.0
```

**Comment by Epochex** [comment]
出现了一样的问题，怎么解决的呀

**Comment by pseudorandom314** [comment]
> 出现了一样的问题，怎么解决的呀

请问这个问题解决了吗

**Comment by Epochex** [comment]
> > 出现了一样的问题，怎么解决的呀
> 
> 请问这个问题解决了吗

解决了，直接用手机号作为用户名，然后整段复制cURL作为密码进去就可以了
